name: API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16-dind
        privileged: true
        options: >-
          --health-cmd="curl --fail http://localhost:8000/ || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 8000:8000

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Build and start Docker containers
        run: |
          docker-compose up -d --build

      - name: Wait for app to be ready
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:8000/; then
              echo "App is ready!"
              exit 0
            fi
            echo "Waiting for app to start..."
            sleep 2
          done
          echo "App did not start in time" >&2
          exit 1

      - name: Run API tests
        run: |
          pytest api-tests/test_api.py
